<a href="https://colab.research.google.com/github/Anusarakh/thesis/blob/main/music_Ex_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
import csv

In [22]:
y, sr = librosa.load(librosa.ex('libri1'))
mfcc_test = librosa.feature.mfcc(y=y, sr=44100, S=None, n_mfcc=20)

In [23]:
y

array([0.00037424, 0.00036333, 0.00024905, ..., 0.00101743, 0.0023917 ,
       0.00200722], dtype=float32)

In [24]:
len(y)

327222

In [25]:
df_ = pd.DataFrame(mfcc_test)
df_

,0,1,2,3,4,5,6,7,8,9,...,630,631,632,633,634,635,636,637,638,639
0,-580.563782,-579.043213,-578.655518,-574.975403,-568.155457,-563.104309,-569.086304,-575.819336,-580.513916,-583.474976,...,-298.780151,-348.419098,-409.945984,-459.451263,-472.340942,-483.382996,-462.628693,-450.105133,-436.670959,-444.143097
1,14.942307,16.862049,16.191315,20.091843,28.848083,36.064285,29.632799,20.243217,13.979107,10.379160,...,200.579620,189.327423,155.025467,112.008667,94.525070,87.141701,92.656128,90.702728,92.955490,95.278473
2,13.763187,15.147621,11.621872,12.518572,19.190315,26.360775,24.533577,15.432577,10.216854,8.124254,...,-3.430164,26.567619,42.077988,32.277191,23.629436,23.060539,3.879772,-3.936304,1.101832,4.415900
3,12.584791,13.479251,7.308465,5.555863,10.279902,16.769608,18.766636,9.928635,6.190442,5.859468,...,14.526033,28.748602,44.746460,38.040031,34.573128,37.558231,31.760437,35.554443,43.287697,38.567375
4,11.935865,12.662352,5.671687,3.335501,7.393722,12.366469,14.633381,6.067735,3.822276,4.702595,...,20.570446,37.111168,42.706284,40.391708,35.173561,40.495567,46.711601,44.787292,31.843426,34.355690
5,11.786961,12.664164,6.987242,6.330148,11.171232,14.222211,13.034028,5.134626,3.899349,4.849620,...,8.954658,10.187418,3.810347,18.359224,15.453938,14.372238,12.705879,9.869893,2.907554,7.592511
6,11.592858,12.668779,9.313227,11.276693,17.454338,18.989939,13.171606,6.851991,5.760449,5.551494,...,-1.961146,-11.351871,-8.624639,8.155287,5.031083,4.187399,0.580451,-1.949898,-6.687394,-8.131956
7,10.744301,11.749119,10.028494,13.789093,20.565689,21.560665,13.363205,9.740936,7.882412,5.774958,...,14.692663,15.282798,19.655682,18.318865,18.902920,22.228121,22.726883,22.336323,17.924215,10.062509
8,9.069759,9.623350,7.786139,11.569662,17.438454,18.743156,12.284746,12.031054,8.890132,4.999216,...,15.166485,10.705410,11.788424,3.870145,8.993621,16.081329,12.654745,11.516973,16.715723,15.911778
9,6.989947,6.899542,3.427038,5.822505,9.541170,11.304214,9.744791,12.534420,8.293473,3.528960,...,2.780458,-2.537200,-7.650374,-12.277519,-3.733739,3.022994,-6.254004,-13.609178,-9.104316,-3.847252
10,5.204023,4.618204,-0.760768,0.001913,1.389886,3.051821,6.524787,11.031198,6.531971,2.121915,...,-6.001768,6.383070,-0.488380,-4.220707,7.494823,7.799723,0.613807,-6.030664,-4.642700,-3.714333
11,4.157882,3.456403,-2.787563,-2.905383,-2.940869,-2.129660,3.561963,8.096720,4.441530,1.287839,...,-19.439865,-16.537083,-10.806915,-7.385108,-5.255231,-1.892720,-1.995951,-6.499100,-3.803783,-7.366666
12,3.715788,3.222559,-2.351731,-2.392667,-2.551635,-2.967891,1.209858,4.637725,2.635882,0.864099,...,-7.641262,-14.000986,-4.195745,-1.986718,-7.651371,-1.151663,0.179254,-1.780735,3.332547,-2.143211
13,3.294033,3.038860,-0.868704,-0.346163,0.206085,-1.287217,-0.840803,1.483308,1.260414,0.218388,...,-8.601791,-3.981104,1.437249,2.349464,-1.211919,0.595394,-1.238413,-3.943380,-3.457577,-5.091106
14,2.348110,2.064330,-0.228620,0.776641,2.008159,-0.161406,-2.999443,-0.795965,0.202370,-1.108664,...,-18.639339,-15.360704,-12.553606,-5.021535,-9.081432,-11.752414,-13.403883,-15.406197,-19.057522,-15.357947
15,0.825368,0.184959,-1.327879,-0.133412,1.152633,-1.363110,-5.134409,-1.899323,-0.543062,-2.883755,...,-9.892307,-7.374737,-2.718650,2.102052,-5.787169,-10.623446,-10.067575,-4.473525,-5.399686,-2.365000
16,-0.775926,-1.874985,-3.509753,-2.297437,-1.533782,-4.128368,-6.466211,-1.790312,-0.739011,-4.251328,...,-2.923307,1.138517,7.609873,9.156607,1.370689,-1.238199,-1.831123,5.774624,5.398546,2.107193
17,-1.787178,-3.108542,-5.257618,-4.069028,-3.898047,-6.071257,-6.136635,-0.738188,-0.138822,-4.373020,...,9.144077,8.363283,6.413422,4.977156,4.174027,0.651619,-3.721475,-0.608476,-3.137721,-5.866878
18,-1.887963,-3.010566,-5.483588,-4.431328,-4.475768,-5.343234,-4.000320,0.678549,1.144185,-3.133708,...,5.288239,0.084013,-3.976909,-3.611831,-3.171042,-6.453978,-8.698851,-8.851712,-10.227419,-12.728681
19,-1.352437,-1.973576,-4.342721,-3.672975,-3.558012,-2.216679,-0.960576,1.731579,2.507824,-1.332142,...,-8.529924,-9.599512,-3.097654,1.646523,0.539659,3.062920,4.275784,1.534101,1.388815,-2.358938

In [59]:
mfcc_mean = mfcc_test.mean()
mfcc_mean

-6.3565636

In [9]:
zcr = librosa.feature.zero_crossing_rate(y)
zcr

array([[0.02929688, 0.046875  , 0.05664062, 0.05419922, 0.04150391,
        0.03125   , 0.03125   , 0.04003906, 0.05957031, 0.06982422,
        0.06933594, 0.05957031, 0.04638672, 0.03173828, 0.02978516,
        0.02539062, 0.02148438, 0.04101562, 0.04003906, 0.06201172,
        0.06640625, 0.05078125, 0.05224609, 0.02929688, 0.02734375,
        0.02441406, 0.01953125, 0.01660156, 0.01416016, 0.015625  ,
        0.02001953, 0.02636719, 0.03076172, 0.03173828, 0.02832031,
        0.02099609, 0.015625  , 0.01904297, 0.02050781, 0.02734375,
        0.02490234, 0.02685547, 0.03076172, 0.03515625, 0.0390625 ,
        0.03466797, 0.02929688, 0.02001953, 0.02001953, 0.01708984,
        0.01757812, 0.01708984, 0.01806641, 0.02392578, 0.02587891,
        0.03076172, 0.03027344, 0.02734375, 0.03271484, 0.03271484,
        0.03955078, 0.04101562, 0.03417969, 0.02832031, 0.02099609,
        0.01806641, 0.01806641, 0.02587891, 0.03271484, 0.03417969,
        0.06005859, 0.11572266, 0.18115234, 0.25244141, 0.28076172,
        0.24560547, 0.18505859, 0.11083984, 0.08691406, 0.07275391,
        0.06689453, 0.07617188, 0.05126953, 0.04638672, 0.04638672,
        0.03857422, 0.03466797, 0.02929688, 0.02734375, 0.02978516,
        0.02636719, 0.03271484, 0.08251953, 0.1640625 , 0.21728516,
        0.21044922, 0.15673828, 0.07080078, 0.01855469, 0.01806641,
        0.02099609, 0.02832031, 0.03076172, 0.02783203, 0.03271484,
        0.05273438, 0.0703125 , 0.11425781, 0.14746094, 0.16064453,
        0.17138672, 0.13916016, 0.10498047, 0.07128906, 0.04882812,
        0.04589844, 0.04785156, 0.05126953, 0.05371094, 0.05615234,
        0.05712891, 0.05517578, 0.04736328, 0.04199219, 0.04101562,
        0.03027344, 0.02929688, 0.03955078, 0.04101562, 0.06054688,
        0.07666016, 0.07421875, 0.09716797, 0.109375  , 0.10791016,
        0.12207031, 0.11572266, 0.11767578, 0.12597656, 0.11767578,
        0.09912109, 0.07275391, 0.05761719, 0.05712891, 0.08740234,
        0.08789062, 0.08251953, 0.06884766, 0.03857422, 0.03662109,
        0.03808594, 0.0390625 , 0.03320312, 0.03564453, 0.03710938,
        0.03271484, 0.03173828, 0.02734375, 0.02099609, 0.01904297,
        0.02001953, 0.0234375 , 0.02636719, 0.03369141, 0.04003906,
        0.04492188, 0.05273438, 0.05273438, 0.05273438, 0.04492188,
        0.03662109, 0.04931641, 0.07666016, 0.11767578, 0.16162109,
        0.18505859, 0.1875    , 0.17578125, 0.13183594, 0.09472656,
        0.06347656, 0.04248047, 0.04443359, 0.04052734, 0.03564453,
        0.02929688, 0.02929688, 0.02929688, 0.02929688, 0.03027344,
        0.02392578, 0.01855469, 0.01611328, 0.00976562, 0.01318359,
        0.01611328, 0.02734375, 0.03710938, 0.04150391, 0.04443359,
        0.03222656, 0.03125   , 0.02587891, 0.02978516, 0.03076172,
        0.02636719, 0.02490234, 0.01855469, 0.02246094, 0.02539062,
        0.03076172, 0.02832031, 0.02246094, 0.02001953, 0.01904297,
        0.02099609, 0.02148438, 0.02001953, 0.02539062, 0.03515625,
        0.04394531, 0.04736328, 0.03662109, 0.02636719, 0.02001953,
        0.02978516, 0.05175781, 0.06396484, 0.06103516, 0.04833984,
        0.02832031, 0.01611328, 0.01806641, 0.03173828, 0.06054688,
        0.12207031, 0.18212891, 0.18847656, 0.16796875, 0.10546875,
        0.04443359, 0.0234375 , 0.01953125, 0.02734375, 0.03222656,
        0.03808594, 0.03857422, 0.03369141, 0.03173828, 0.0390625 ,
        0.08642578, 0.15625   , 0.22998047, 0.29980469, 0.32421875,
        0.31542969, 0.27490234, 0.19775391, 0.12304688, 0.06054688,
        0.02734375, 0.01953125, 0.01660156, 0.01708984, 0.01318359,
        0.01660156, 0.0234375 , 0.02734375, 0.03417969, 0.03271484,
        0.02880859, 0.02783203, 0.02880859, 0.05078125, 0.10644531,
        0.15869141, 0.16113281, 0.140625  , 0.08447266, 0.03320312,
        0.02929688, 0.02685547, 0.02490234, 0.03320312, 0.02783203,
        0.03076172, 0.03173828, 0.01757812, 0.01708984, 0.01318359,
        0.01708984, 0.0234375 , 0.02978516, 0.03857422, 0.04296875,
        0.04931641, 0.05371094, 0.05126953, 0.04541016, 0.03710938,
        0.02783203, 0.02148438, 0.01806641, 0.01855469, 0.01757812,
        0.05712891, 0.13671875, 0.22265625, 0.31152344, 0.34619141,
        0.27001953, 0.18457031, 0.10205078, 0.02929688, 0.02539062,
        0.02246094, 0.01757812, 0.0234375 , 0.02978516, 0.03027344,
        0.02832031, 0.02197266, 0.01513672, 0.01513672, 0.02636719,
        0.03369141, 0.03955078, 0.04833984, 0.0390625 , 0.03369141,
        0.02783203, 0.02001953, 0.06738281, 0.15820312, 0.24462891,
        0.30712891, 0.28173828, 0.19140625, 0.11328125, 0.07519531,
        0.07421875, 0.1015625 , 0.12060547, 0.12255859, 0.13330078,
        0.13867188, 0.13769531, 0.13525391, 0.12841797, 0.11865234,
        0.09619141, 0.06982422, 0.04101562, 0.01708984, 0.01806641,
        0.02441406, 0.03417969, 0.03857422, 0.05810547, 0.05908203,
        0.05664062, 0.05566406, 0.04248047, 0.04638672, 0.05029297,
        0.05273438, 0.05322266, 0.04833984, 0.04443359, 0.0390625 ,
        0.03271484, 0.02734375, 0.02294922, 0.02246094, 0.02148438,
        0.02636719, 0.03222656, 0.02978516, 0.03027344, 0.03027344,
        0.03125   , 0.03369141, 0.03369141, 0.02783203, 0.02197266,
        0.01855469, 0.01367188, 0.01416016, 0.01904297, 0.02441406,
        0.03076172, 0.03808594, 0.04052734, 0.04101562, 0.04003906,
        0.04101562, 0.03271484, 0.02636719, 0.02099609, 0.01660156,
        0.02148438, 0.02636719, 0.03125   , 0.03125   , 0.02929688,
        0.03222656, 0.03320312, 0.03710938, 0.04199219, 0.04248047,
        0.04638672, 0.04589844, 0.04589844, 0.04394531, 0.03955078,
        0.03320312, 0.02978516, 0.03027344, 0.04443359, 0.06982422,
        0.09228516, 0.11425781, 0.09960938, 0.07763672, 0.0703125 ,
        0.05761719, 0.07861328, 0.09814453, 0.09863281, 0.11132812,
        0.11621094, 0.11425781, 0.11767578, 0.12353516, 0.11328125,
        0.10253906, 0.08935547, 0.0625    , 0.04541016, 0.03613281,
        0.02880859, 0.02685547, 0.02978516, 0.04003906, 0.0390625 ,
        0.03515625, 0.03076172, 0.0234375 , 0.02929688, 0.03076172,
        0.02832031, 0.03173828, 0.12158203, 0.22753906, 0.33300781,
        0.41601562, 0.33105469, 0.22363281, 0.12109375, 0.03857422,
        0.03222656, 0.0390625 , 0.04492188, 0.04052734, 0.0390625 ,
        0.04003906, 0.04052734, 0.03710938, 0.03271484, 0.02929688,
        0.02685547, 0.02636719, 0.02636719, 0.02294922, 0.02050781,
        0.02050781, 0.05029297, 0.08349609, 0.09716797, 0.10595703,
        0.08398438, 0.05664062, 0.04833984, 0.04589844, 0.046875  ,
        0.04833984, 0.04833984, 0.04052734, 0.03271484, 0.02734375,
        0.02294922, 0.03369141, 0.04345703, 0.04785156, 0.04931641,
        0.04052734, 0.02929688, 0.02441406, 0.03857422, 0.06689453,
        0.08300781, 0.08154297, 0.06152344, 0.03027344, 0.01660156,
        0.01611328, 0.01806641, 0.01953125, 0.01953125, 0.01855469,
        0.01611328, 0.02001953, 0.01953125, 0.02392578, 0.03417969,
        0.07617188, 0.12744141, 0.12792969, 0.12207031, 0.08056641,
        0.03857422, 0.04541016, 0.04296875, 0.04785156, 0.08447266,
        0.12158203, 0.1640625 , 0.18408203, 0.13720703, 0.09130859,
        0.04785156, 0.01708984, 0.01660156, 0.01367188, 0.01318359,
        0.01513672, 0.01904297, 0.01855469, 0.01757812, 0.01367188,
        0.01220703, 0.02197266, 0.03466797, 0.04345703, 0.04101562,
        0.03369141, 0.02587891, 0.02246094, 0.02490234, 0.02441406,
        0.02099609, 0.02001953, 0.02050781, 0.02783203, 0.03125   ,
        0.03320312, 0.03759766, 0.03662109, 0.03808594, 0.03515625,
        0.02783203, 0.02001953, 0.01464844, 0.01220703, 0.01367188,
        0.02050781, 0.02880859, 0.0390625 , 0.046875  , 0.04443359,
        0.03808594, 0.03369141, 0.02734375, 0.02636719, 0.04980469,
        0.08886719, 0.12890625, 0.17382812, 0.19384766, 0.18896484,
        0.16796875, 0.12890625, 0.09179688, 0.06445312, 0.05566406,
        0.05371094, 0.04931641, 0.04150391, 0.03271484, 0.02832031,
        0.02978516, 0.03222656, 0.03515625, 0.03759766, 0.03759766,
        0.03710938, 0.04101562, 0.03857422, 0.03271484, 0.03076172,
        0.02539062, 0.02392578, 0.02783203, 0.04394531, 0.06298828,
        0.07910156, 0.08203125, 0.06933594, 0.05224609, 0.04248047,
        0.046875  , 0.04833984, 0.04980469, 0.04931641, 0.04492188,
        0.04199219, 0.03857422, 0.03125   , 0.02441406, 0.02246094,
        0.02685547, 0.03320312, 0.03955078, 0.04492188, 0.03955078,
        0.04052734, 0.04199219, 0.03759766, 0.03808594, 0.03125   ,
        0.02246094, 0.01904297, 0.01660156, 0.01757812, 0.01660156,
        0.03564453, 0.05126953, 0.06445312, 0.06689453, 0.04345703]])

In [10]:
df_zero = pd.DataFrame(zcr)
df_zero

,0,1,2,3,4,5,6,7,8,9,...,630,631,632,633,634,635,636,637,638,639
0,0.029297,0.046875,0.056641,0.054199,0.041504,0.03125,0.03125,0.040039,0.05957,0.069824,...,0.022461,0.019043,0.016602,0.017578,0.016602,0.035645,0.05127,0.064453,0.066895,0.043457

In [61]:
zcr_mean = zcr.mean()
zcr_mean

0.05833511352539063

In [35]:
import matplotlib.pyplot as plt
import scipy

In [43]:
lpc_test = librosa.lpc(y, order=1, axis=-1)
lpc_test

array([ 1.       , -0.9879697], dtype=float32)

In [44]:
df_lpc_test = pd.DataFrame(lpc_test)
df_lpc_test

         0
0  1.00000
1 -0.98797

In [62]:
lpc_test_mean = lpc_test.mean()
lpc_test_mean

0.0060151517

In [48]:
spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
spec_cent

array([[1948.53353543, 2065.75323454, 2108.69876753, 1940.67974686,
        1432.97012779, 1220.54620448, 1424.06811688, 1878.26750961,
        2019.98083004, 2392.98583544, 2143.85684057, 1773.82589143,
        1414.4036827 ,  977.48092965,  478.65798467,  555.13839594,
         675.54403021,  666.94888272,  641.9794709 , 1641.02501568,
        2182.31101546, 1040.99756461,  666.74507808,  701.19562093,
         658.53126068,  556.41104492,  484.02689886,  409.69151355,
         362.55139566,  360.07805904,  418.70314748,  547.45730946,
         639.73801207,  639.82683927,  598.56218605,  633.54585978,
         725.6159755 ,  677.06635433,  580.36914101,  694.17553202,
         850.27198308, 1421.56952594, 1316.58107483, 1263.50715845,
        1095.54530615,  818.65173713,  832.01570854,  871.74222318,
         859.26670021,  774.52719562,  714.90333639,  621.49940042,
         484.68363235,  407.88364609, 1217.12929656, 1386.54852844,
        1074.97338673,  771.66860782, 1027.09485578,  964.24699243,
         894.34066882,  963.57032816,  959.86236499,  842.7927854 ,
         687.63722561,  772.94130517,  735.25808623,  692.33978307,
         707.75250599,  704.50710106,  720.20274021, 1252.22259252,
        2612.30210964, 3360.29621064, 3564.07260145, 3490.25861671,
        3114.6346441 , 2369.41221271, 2392.98352239, 2091.50416289,
        1195.8357118 ,  792.28610546,  836.09667435,  817.9819319 ,
         831.03194922,  805.36090924,  742.65400467,  617.60652219,
         644.70379415,  721.12173473,  697.44063237,  608.72215519,
         790.33905083, 2739.08937378, 3725.29182888, 3298.17961344,
        2445.51216297,  970.95177695,  600.43487413,  665.79899757,
         638.43416005,  591.53342382,  547.12770284,  509.59300947,
         448.44935264,  782.69087979, 1461.17912976, 1747.5708873 ,
        2205.82885433, 2595.34155232, 2852.32685241, 2842.32276121,
        1736.78891261, 1104.0177565 ,  797.77457321,  695.48415181,
         728.44807259,  743.04071811,  739.70523132,  744.20341771,
         821.53525878, 1072.29502815, 1589.43591186, 2183.56990547,
        2163.81128672, 1703.1510421 ,  989.11626551, 1018.03924274,
        1276.84268793, 1450.49585653, 1545.59790651, 1580.16691279,
        1621.79883342, 1718.58025864, 1836.06958543, 1762.36264602,
        1694.85171725, 1835.9137885 , 1831.05909823, 1703.12974905,
        1539.58406573, 1454.0324884 , 1368.65323471, 1297.14615359,
        1938.44424652, 1787.26087706, 1074.61310904, 1221.04285977,
        1384.39797209, 1207.54514093, 1100.74182208, 1237.51191824,
        1341.87039475, 1242.04653738, 1285.96292667, 1223.99598506,
        1027.23066134,  731.27106997,  588.79387612,  526.57910661,
        1197.82184635, 1407.89583096,  846.32507239,  599.24089641,
         619.17548526,  704.77929116,  771.84042784,  770.86802888,
         753.65422458,  742.24886854,  708.26143962,  821.22981637,
        1379.64895193, 1892.87135322, 2350.03833016, 2493.69079753,
        2507.41938408, 2359.22927154, 1852.07608758,  966.12303467,
         961.71356299, 1056.62687264, 1027.12177301,  913.43202766,
         834.4021869 ,  752.97280425,  659.63477079,  546.72040975,
         502.92517406,  508.95762981,  477.79872251,  458.12526945,
         541.18888237,  558.52408489,  550.40282688,  714.23513712,
         997.43439689, 1227.23383423, 1231.85635537, 1372.69611541,
        1284.63463158, 1169.69783833, 1154.54027882, 1324.05609157,
        1309.51934439, 1185.54124108,  498.90700421,  382.66107821,
         482.9335912 ,  538.69019026,  559.7051307 ,  575.32803669,
         645.21563762,  743.24948947,  735.53742969,  668.34315789,
         603.70758052,  480.41763769,  541.50607618, 1972.43117697,
        2566.36040075, 1851.80348499, 1230.68755376,  835.14933563,
         590.23168536, 1263.72244702, 1628.54453169, 1568.01232445,
        1296.29857323,  731.19275145,  702.91009191,  653.43823218,
         530.92828454,  563.56278349,  904.89575694, 1802.87142327,
        2898.620564  , 3115.77984903, 2634.9596406 , 1241.9714704 ,
         635.00949465,  609.01047952,  622.21856596,  643.0725236 ,
         627.10395434,  603.52336929,  620.4999018 ,  609.244165  ,
         575.19547399,  551.08586535, 1084.03045261, 2238.11322762,
        3141.30124901, 3523.35708126, 3843.36002824, 4034.45920337,
        3868.55407125, 2140.13982964, 1308.0969066 ,  989.24279028,
        1004.37492084, 1044.80041655,  855.48988224,  614.92377877,
         574.38577119,  580.42453396,  598.67790997,  646.80641906,
         667.64088691,  647.99733296,  638.99813738,  687.06077814,
         900.27342751, 1583.91921504, 2221.70503919, 2592.56256688,
        3091.7795984 , 1396.35545961,  684.21443004,  757.2969078 ,
         855.04383035,  854.15479824,  711.70683909,  576.48522551,
         667.79170205, 1170.04742033, 1149.79423803,  731.66766322,
         533.47969654,  372.09570192,  492.7730858 , 1197.83412641,
        1042.20735968,  812.77658459,  737.99716706,  709.843514  ,
         771.64672085,  818.11314104,  834.41489692,  856.00851156,
         754.16780554,  568.31175294,  487.91982724,  588.21221572,
         733.13211666,  859.75465943, 1924.56545366, 3474.9176912 ,
        4022.44950614, 4112.26560248, 3574.25730247, 1708.92759276,
         790.19342268,  695.74138156,  597.55420954,  563.24145592,
         568.81567952,  579.76101808,  642.10120875,  645.88262442,
         590.28297453,  596.00582924,  603.63428799,  579.72828295,
         593.17231969,  660.53748473,  696.4971506 ,  700.61122478,
         712.72387336,  674.80754827,  645.18000214,  556.20148923,
         676.19798136, 1627.36507257, 3896.9237103 , 4269.47273026,
        4005.64949691, 3159.72538978, 2044.07452409, 1722.13707861,
        1637.99789805, 1708.0396491 , 1749.50836314, 1795.94010235,
        1806.91857387, 1821.89013055, 1897.02773728, 1744.31559433,
        1632.59298139, 1659.06338485, 1732.88110205, 1755.53716097,
        1594.87198792,  929.19751835,  829.53931147, 1054.55716656,
        1333.88724053, 1505.71151187, 1418.64072622, 1424.4768806 ,
         776.25877016,  533.64824464,  592.63725162,  665.77212743,
         709.86863891,  723.81504682,  756.10511886,  816.29862878,
         905.78106263,  914.07946104,  888.7853744 ,  874.63855241,
         847.19476287,  632.45837675,  629.86363961,  664.79735179,
         677.68364493,  671.92546158,  596.29381061,  487.01025578,
         916.77968933, 1418.47726247,  850.0026495 ,  828.34775669,
         847.93308919,  628.11010651,  524.17295235,  453.89835931,
         789.27951826, 1011.98702722,  924.89006688,  902.56529233,
         928.85830219,  895.06085968,  835.49827399,  756.56175276,
         691.91569553,  660.03569165,  629.49465248,  584.95711258,
         607.85954518,  639.73212223,  548.38822887,  474.30096644,
         439.5674616 ,  440.81927155,  531.49785878,  598.27241998,
         677.4498982 ,  748.72863381,  795.89487043,  795.90566821,
         797.18566059,  805.72148151,  792.69253284,  710.44751747,
         595.4578932 ,  513.3806679 ,  914.54688487, 2667.5684907 ,
        2674.63831589, 2571.01327856, 2162.83818276, 1866.54530576,
        1323.66439262, 1124.47938932, 1308.57942694, 1522.18629678,
        1700.98529978, 1728.29063922, 1705.1456361 , 1733.54032302,
        1683.97896318, 1715.23250149, 1863.16464992, 1754.73126436,
        1662.75300527, 1529.17333407, 1461.96375337, 1112.72267635,
         789.49546736,  874.01634439,  944.47995755, 1085.68840358,
        1032.24606903,  927.21212336,  762.94406642,  788.49129752,
         852.07233732,  872.57335099,  837.36707555,  711.11186814,
        1127.04082327, 2946.35767259, 4346.99354391, 4673.16820143,
        4546.1675629 , 3216.68526056, 1367.25620395,  958.34499593,
         891.41413809,  792.212361  ,  812.63375116,  768.54292721,
         706.75140329,  617.17991591,  696.42899924,  796.89692167,
         595.67012837,  532.94781665,  695.70886043,  943.62528743,
        1135.04429987, 1074.49494896,  811.89608821,  848.32199344,
        1826.09071186, 2261.26461669, 2243.14039553, 1954.3488603 ,
         876.72302928,  737.3568815 ,  831.27587969,  856.2466342 ,
         828.17765663,  841.60119005,  897.18218302,  963.82560723,
         894.10888373,  759.79582054,  802.39413479,  836.65310817,
         886.57044701,  919.32358066,  912.1307703 ,  858.76753817,
         778.51872117,  609.06838376,  496.1568425 , 1427.6166892 ,
        2005.68258316, 1657.32712606,  772.58427544,  647.49747631,
         683.76963306,  715.37243591,  771.7058005 ,  781.56308457,
         848.16707734,  888.34443129,  853.48641035,  745.11223822,
         743.22710624,  666.35106653,  580.6795206 , 1957.63482825,
        2419.43828447, 2573.84608477, 1420.25661172, 1003.55269403,
        1120.5093593 , 1208.4872105 , 1196.79771462, 1097.90734553,
        1054.79777087, 1667.43202631, 2382.14084591, 2406.8333368 ,
        1715.96146927,  825.24005465,  747.00867929,  619.34235695,
         495.14860336,  427.9464518 ,  362.06272912,  867.95197688,
        1288.92895046,  997.49466745,  910.48889942,  711.86874886,
         505.22127776, 1192.10475709, 1244.66496779, 1240.06635293,
         889.18403888,  544.48602139,  596.19428957,  752.16130208,
         883.8469264 ,  918.18244872,  859.57324279,  602.74886298,
         489.97579126,  563.16696162, 1034.95676579, 1061.33943649,
        1115.30925476, 1144.0471683 , 1079.53082646,  943.09237095,
         722.61280592,  615.26009905,  519.16740755,  589.38214552,
         998.04192282,  842.02328114,  646.75659363,  654.31451916,
         695.56148347,  747.56598887,  729.74513649,  706.68388727,
         767.0784214 ,  714.35692193,  670.79173993, 1066.60387668,
        1880.86849348, 2301.91465322, 2381.42836645, 2345.19641071,
        2233.8702294 , 1419.22555871,  901.31526715,  976.73674342,
        1137.68640655, 1173.0438545 , 1086.57653847,  982.30454615,
         862.11124494,  719.23749764,  610.39582051,  520.2008998 ,
         528.11921051,  747.08420918,  846.62207649,  916.52442145,
        1010.14721494, 1011.67946853,  863.03314372,  647.39189269,
         586.89922407,  619.52653435,  752.31750335, 1166.19707198,
        1152.83412293, 1364.6705134 , 1468.84222868,  723.02221456,
         684.32953119,  772.75008298,  779.53690541,  812.87517897,
         835.41583514,  918.19168738,  948.10446114,  961.11076645,
         911.57851271,  874.67542329,  728.72725347,  584.47920489,
         640.50385737,  744.68016496,  800.49678741,  821.89851304,
         795.00164486,  842.7317518 ,  851.9599894 ,  861.49591071,
         834.03158385,  722.61523962,  564.6192523 ,  444.88231883,
         473.51061083,  818.02712908, 1116.74667712, 1071.7523328 ,
        1213.87596491, 1509.85606625, 1550.39171525, 1497.81028711]])

In [66]:
spec_cent_mean = spec_cent.mean()
spec_cent_mean

1147.2592587922977

In [50]:
df_spec_cent = pd.DataFrame(spec_cent)
df_spec_cent

,0,1,2,3,4,5,6,7,8,9,...,630,631,632,633,634,635,636,637,638,639
0,1948.533535,2065.753235,2108.698768,1940.679747,1432.970128,1220.546204,1424.068117,1878.26751,2019.98083,2392.985835,...,564.619252,444.882319,473.510611,818.027129,1116.746677,1071.752333,1213.875965,1509.856066,1550.391715,1497.810287

In [52]:
time_step = 1

In [55]:
Power_Spectrum = np.fft.fftfreq(y.size, time_step)
Power_Spectrum

array([ 0.00000000e+00,  3.05602924e-06,  6.11205848e-06, ...,
       -9.16808772e-06, -6.11205848e-06, -3.05602924e-06])

In [58]:
df_Power_Spectrum = pd.DataFrame(Power_Spectrum)
df_Power_Spectrum

               0
0       0.000000
1       0.000003
2       0.000006
3       0.000009
4       0.000012
...          ...
327217 -0.000015
327218 -0.000012
327219 -0.000009
327220 -0.000006
327221 -0.000003

[327222 rows x 1 columns]

In [67]:
Power_Spectrum_mean = Power_Spectrum.mean()
Power_Spectrum_mean

-1.5280146200513542e-06

#สร้างตาราง

In [81]:
name = [{'mfcc_mean':'-6.3565636', 'lpc_test_mean':'0.0060151517', 'spec_cent_mean':'1147.2592587922977', 'zcr_mean':'0.05833511352539063', 'Power_Spectrum_mean':'-1.5280146200513542e-06'}]

In [78]:
data_ = [[-6.3565636], [0.0060151517], [1147.2592587922977], [0.05833511352539063], [-1.5280146200513542e-06]]
data_

[[-6.3565636],
 [0.0060151517],
 [1147.2592587922977],
 [0.05833511352539063],
 [-1.5280146200513542e-06]]

In [82]:
data_set = pd.DataFrame(name)
data_set

,mfcc_mean,lpc_test_mean,spec_cent_mean,zcr_mean,Power_Spectrum_mean
0,-6.3565636,0.0060151517,1147.2592587922977,0.05833511352539063,-1.5280146200513542e-06